/**
 * 
 */
define({

	// added search sequence number
	delegation_management: "ادارة التفويض",
	reassign_management:"ادارة نقل المعاملات",
	permissionsOwner:"استعراض ملاك الصلاحيات",
	prepared_by_title:"الجهة المعدة للخطاب وتكون داخلية",
	INTERNAL_CREATED_SOURCE:"الجهة المنشأة",
	CIRCULATE_SUBJECT_LABEL:"موضوع التعميم",
	CIRCULATE_NO_LABEL:"رقم التعميم ",
	CIRCULATE_TYPE_LABEL:"نوع التعميم",
	DECISION_SUBJECT_LABEL:"موضوع القرار ",
	DECISION_TYPE_LABEL:"نوع القرار",
	DECISION_NO_LABEL:"رقم القرار",
	searchSequence : "بحث",
	searchSeqNumber : "التصفية برقم المعاملة او جزء من الموضوع",
	RIGHT_SCAN_BLACK : "المسح الضوئي الأسود",
	RIGHT_SCAN_GRAY : "المسح الضوئي الرمادي",
	RIGHT_SCAN_COLOR : "المسح الضوئي الملون",
	RIGHT_SEND_OUTGOING_WITH_OLD_DATE : "إرسال معاملة صادر بتاريخ قديم",
	RIGHT_CREATE_GENERALIZATIONS : "الإطلاع على مرفقات المعاملات عبر شاشة البحث",
	RIGHT_SEND_WITHOUT_ATTACHMENTS : "إرسال الصادر والوارد بدون مرفقات",
	RIGHT_CREATE_STATISTICAL_REPORTS : "صلاحية إنشاء تقارير إحصائية",
	RIGHT_FOLLOWUP_REMINDER : "التذكير بمتابعة المعاملات",
	RIGHT_DEPT_SEARCH_OPTION : "البحث في معاملات الإدارة",
	RIGHT_MAIN_DEPARTMENT_MANAGER : "صلاحية مدير وكالة",
	RIGHT_EDIT_OUTGOING : "تعديل معاملات الصادر الخارجي",
	RIGHT_EDIT_INCOMING : "تعديل معاملات الوارد الخارجي",
	RIGHT_EDIT_INTERNAL : "تعديل المعاملات الداخلية",
	RIGHT_FULL_SEARCH_OPTION : "البحث في معاملات الامانة",
	RIGHT_MANAGER_PERMISSION : "صلاحيات مدير الإدارة في المراسلات",
	RIGHT_SHOW_CONFIDENTIALITY_SECURE : "الإطلاع على المعاملات السرية",
	RIGHT_SHOW_CONFIDENTIALITY_VERY_SECURE : "الإطلاع على المعاملات السرية جداً",
	RIGHT_SHOW_CONFIDENTIALITY_EXTREME_SECURE : "الإطلاع على المعاملات السرية للغاية",
	RIGHT_COMMUNICATE_ALL_EMPLOYEE : "مخاطبة جميع الموظفين",
	RIGHT_EDIT_CORR_DETAILS : "تعديل معلومات المعاملة",
	RIGHT_EDIT_CORR_ATTACHMENTS : "تعديل مرفقات المعاملة",
	RIGHT_EDIT_CORR_RESEND : "تعديل -  إعادة إرسال المعاملات",
	RIGHT_END_CORRESPONDENCE : "صلاحية إنهاء و حفظ المعاملة",
	RIGHT_DELETE_HISTORY_AND_WORITEMS : "صلاحية الحذف من سجل الإحالات و عناصر العمل",
	RIGHT_REMINDER_MESSAGE : "صلاحية رسالة التذكير",
	RIGHT_DEADLINE : "صلاحية اخر موعد",
	RIGHT_EXPORT : "صلاحية التصدير",
	RIGHT_CREATE_OUTGOING : "إنشاء صادر خارجي",
	RIGHT_CREATE_INCOMING : "إنشاء وارد خارجي",
	RIGHT_CREATE_INTERNAL : "إنشاء معاملة داخلية",
	RIGHT_Department_Represented : "جعل ممثل الإدارة هو من يستلم معاملات الإدارة",
	RIGHT_CREATE_DECESIONS : "إنشاء قرارات",
	RIGHT_CREATE_CIRCULARS : "إنشاء تعاميم",
	canAccessSystemLable : "امكانية التفاعل مع النظام؟",
	ldap_inquiry : "استعلام من الدليل النشط",
	Employee_Infomration : "معلومات الموظف",
	Powers_Granted : "الصلاحيات الممنوحة",
	Customized_Forwarding_List : "تحديد جهات المراسلة",
	substitute_employee : "الموظف البديل",
	Records_Management : "الموظفين/الادارات",
	ManageEmployees : "ادارة سجلات الموظفين",
	InbasketMembers : "اعضاء الصندوق المشترك",
	ManagePublicInbasketMembers : "ادارة اعضاء الصناديق المشتركة",
	ManagePublicInbasket : "ادارة الصناديق المشتركة",
	PublicInbasket : "الصناديق المشتركة",
	DeptsAdministration : "ادارة سجلات الادارات",
	Committees_Management : "اللجان",
	Site_Management : "إدارة الموقع",
	CommitteesAdministration : "ادارة سجلات اللجان",
	VariablesAdministration : "إدارة متغيرات النظام",
	CorrespondenceTypeAdmin : "إدارة نوع المعاملة",
	CorrespondenceCategoryAdmin : "إدارة تصنيف المعاملة",
	CorrespondenceConfedentialityAdmin : "إدارة سرية المعاملة",
	CorrespondenceRecieveWayAdmin : "إدارة طريقة إستلام المعاملة",
	PrintAttachmentFooterAdmin : "إدارة طباعة مرفقات المعاملة من شاشة البحث",
	isPrintDate : "تاريخ الطباعة",
	isUserID : "اسم المستخدم",
	Code : "الكود",
	CORRESPONDENCETYPEDESC : "نوع المعاملة",
	RECEIVEMODEDESC : "طريقة الإستلام",
	CONFIDENTIALITYDESC : "السرية",
	CORRESPONDENCECATEGORYDESC :"تصنيف المعاملة",
	CommitteesMembers_Administration : "ادارة سجلات اعضاء اللجان",
	CommiteeMembers : "اعضاء اللجنة",
	GROUPID : "رمز المجموعة",
	GROUPNAME : "اسم المجموعة",
	GroupMembers : "اعضاء المجموعة",
	Group_Management : "المجموعات",
	ManageGroups : "ادارة سحلات المجموعات",
	ManageGroupMembers : "ادارة افراد المجموغات",
	ManageDestination : "ادارة الجهات الخارجية",
	ManagePhysicalAttachments : "ادارة انواع سجلات المشفوعات",
	ManageBarcode : "ادارة الباركود",
	ManageReportBanners : "ادارة شعارات التقارير",
	destinationID : "رمز الجهة",
	DestinationNAME : "اسم الجهة",
	DestinationTYPE : "نوع الجهة",
	committeeDescription : "وصف للجنة",
	ManageApplicationLables : "ادارة تسميات التطبيق",
	ManageMessages : "ادارة رسائل التطبيق",
	ManageInboxSettingColorsHTML : "ادارة الوان الصندوق",
	User_List : "قائمة المستخدمين",
	UserList_setIntroText : "وصف لقائمة المستخدمين",
	SubjectID : "رمز الموضوع",
	SubjectText : "نص الموضوع",
	EmployeeID : "رمز الموظف",
	EmployeeName : "اسم الموظف",
	InstructionID : "رمز التوجيه",
	InstructionText : "نص التوجيه",
	AttachmentID : "الرمز",
	AttachmentText : "النوع",
	Othertables : "ادارة سجلات النظام",
	ManageSubjects : "ادارة نصوص المواضيع",
	ManageInstructions : "ادارة نصوص التوجيهات",
	This_Correspondance_is_not_exist : "هذه المعاملة غير موجودة او لا يوجد لك صلاحية عليها",
	Error_Title : "رسالة خطأ",
	ExportCOnfimrationlable : "موافق",
	AreYouShureToExportCorrespondfance : "هل انت متأكد من تصدير هذه المعاملة الى الجهات التي اخترتها مسبقا",
	Cancelof_ExportCOnfimrationlable : "الغاء",
	ConfirmationTitle : "التأكيد على تصدير المعاملة",
	Notfication_ConfirmationTitle : "التأكيد",
	Notfication_Mesage_Keep_Yes_No : "هذه الرسالة ستحذف من صندوقك الخاص, اضغط الغاء اذا ارد ابقائها",

	Inbox_Settings_has_been_saved_sucessfully : "تم حفظ إعدادات صندوق البريد بنجاح",

	The_Internal_Correspondance_with_No : "المعاملة الداخلية التي تحمل رقم",
	The_Circulating_Correspondance_with_No : "معاملة التعميم الذي يحمل رقم",
	The_Decision_Correspondance_with_No : "معاملة القرارالذي يحمل رقم",
	Correspondence_Successfully_Exported : "قد تم بنجاح تصديرها كمعاملة صادر عام برقم",
	Correspondence_is_already_Exported : "تم بالسابق تصدير المعاملة ",
	ExportStatus : "حالة تصدير المعاملة",
	Do_You_Want_to_Open_exported_Correspondance : "هل تريد استعراض المعاملة المصدرة",
	Yes_Confimration : "نعم",
	No_Confimration : "لا",
	and_Number : "رقم",
	and_Date : "بتاريخ",
	and_year : "لسنة",
	error_on_Select_TO_Date : "حدث خطأ من عدم اختيار الى تاريخ",
	error_on_Select_From_Date : "حدث خطأ من عدم اختيار من تاريخ",
	error_on_Select_The_Observer_from_The_List : "حدث خطأ من عدم اختيار المتابع من القائمة",
	error_on_Select_Followup_CheckList : "حدث خطأ من عدم اختيار فترة المتابعة",
	error_on_Select_Delegating_Check : "حدث خطأ من عدم اختيار فترة التفويض",

	error_no_Outgoing_transfered_workflow_found : "حدث خطأ، لم يتم العثور على مسار العمل خاص باجراء العمل للصادر",
	error_no_Incoming_transfered_workflow_found : "حدث خطأ، لم يتم العثور على مسار العمل خاص باجراء العمل للوارد",
	error_no_Internal_transfered_workflow_found : "حدث خطأ، لم يتم العثور على مسار العمل خاص باجراء العمل للداخلي",

	error_URL_parameter_for_Outgoing_workClassName_is_missing : "حدث خطأ بسبب فقدان احد اقسام عنوان رابط الاتصال من اجراء العمل للصادر",
	error_URL_parameter_for_Incoming_workClassName_is_missing : "حدث خطأ بسبب فقدان احد اقسام عنوان رابط الاتصال من اجراء العمل للوارد  ",
	error_URL_parameter_for_Internal_workClassName_is_missing : "حدث خطأ بسبب فقدان احد اقسام عنوان رابط الاتصال من اجراء العمل للاحالات الداخلية ",

	error_Message_for_export_did_not_Add_any_destination : "حدث خطاء, حيث لم يتم اختيار جهة او اكثر من الجهات الخارجية لتصدير المعاملة لها",

	error_Can_not_Delete_Employee_Still_Has_Correspondance_in_his_inbox : "حدث خطأ, لا يمكن حذف الموظف من النظام حيث انه ما زال هناك معاملات في صندوق بريده غير مكتمله بعد!!",

	error_Can_not_Delete_Employee_He_Has_Backup : "حدث خطأ , يوجد للموظف بديل , قم بازالة بديله اولا",
	error_Can_not_Delete_Employee_He_is_a_Backup : "حدث خطأ, هذا الموظف هو بديل لموظف اخر, قم بالغائه كبديل اولا",
	error_Can_not_Delete_Employee_He_is_a_Manager : "حدث خطأ , لا يمكن حذف موظف بموقع اداري قبل ان تعين مدير اخر ",

	error_Can_not_Delete_Employee_He_is_a_member_of_community_or_more : " حدث خطأ, لا يمكن حذف الموظف لانه عضو في لجنة او اكثر , قم بازالة الموظف من اللجان التي ينتمي اليها اولا لكي تتمكن من حذف الموظف ",
	processRoleName : "Moamalat Inbox",
	appSpaceName : "Moamalat Application Spaces",
	inboxQueueName : "My Inbox",
	OutgoingDestinations : "الجهات الخارجية",
	Add_another_OutgoingDestinations : "اختيار جهات اخرى لتصدير المعاملة",
	Exit : "خروج",
	Incoming_correspondence_hlabel : "معاملة واردة",
	outgoing_correspondence_hlabel : "معاملة صادرة",
	Internal_correspondence_hlabel : "معاملة داخلية",
	AddToDestination : "إضافة إلى وجهتها ",
	DestinationName : "اسم الجهة الخارجية",
	SentVia : "طريقة الارسال",
	letterType : "نوع الخطاب",
	ExternalUnits : "وحدات خارجية",
	ExternalGroups : "المجموعات الخارجية ",
	ExportCorrepsondence : "تصدير المعاملات",
	Details : "تفاصيل",
	Print_Enquiry_Ticket : "تذكرة المراجعة",
	Source : "الجهة",
	Forwarding_Details : "الجهات المصدرة لها",
	ReadTask : "متحقق",
	unReadTask : "غير-متحقق",
	update : "تعديل",
	Incoming_correspondence : "معاملة واردة",
	outgoing_correspondence : "معاملة صادرة",
	Internal_correspondence : "معاملة داخلية",
	Decision : "قرار",
	Reminder_for_incoming : "تذكير بمعاملة واردة",
	Reminder_for_outgoing : "تذكير بمعاملة صادرة",
	Reminder_for_internal : "تذكير بمعاملة داخلية",
	CC_for_incoming : "صورة من معاملة واردة",
	CC_for_outgoing : "صورة من معاملة صادرة",
	CC_for_internal : "صورة من معاملة داخلية",
	CC_for_circular:"صورة من تعميم",
	CC_for_decision:"صورة من قرار",
	Read_response_notification : "إشعار قراءة",
	urgent : "عاجل",
	topurgent : "هام و عاجل جدا",
	important : "هام",
	Reminder : "تذكير",
	ccCorresp : "صورة من معاملة",

	WorkItem_read : "تمت قراءتها",
	completed : "منجز",
	Inprogress : "قيد التنفيذ",
	WorkItem_Unread : "غير مقروءة",

	newCr : "جديد",
	circulation : "تعميم",
	Geneate_print_barcode : "إنشاء ملصق الباركود",
	GenerateBarcode_label : "طباعة الباركود",
	Geneate_Print_Barcode_For_Correspondence : "طباعة الباركود",
	correspondance_Type : "نوع المعاملة",
	Readresponse_Message_Word1_for_INCOMING : "المعاملة الواردة ",
	Readresponse_Message_Unknown_Currespondance_Type : "المعاملة ",
	Readresponse_Message_Word1_for_OUTGOING : "المعاملة الصادرة ",
	referenced_correspondence : "ربط المعاملات",
	Label_Internal_Outgoing : "داخلي رقم",
	Label_Correspondence_Date : "تاريخ المعاملة",
	Label_Attachments : "المرفقات",
	Print : "طباعة",
	Readresponse_Message_Word1 : "المعاملة الداخلية ",
	Readresponse_Message_Word2 : "رقم ",
	Readresponse_Message_Word3 : "و موضوعها ",
	Readresponse_Message_Word4 : "قد تمت قرائتها من المستخدم ",
	Readresponse_Message_Word5 : "بتاريخ ",
	Readresponse_Message_Word6 : "الساعة ",
	CurrentSystemDateisnotHijiry : "حدث خطاء بسبب عدم اختيار  تقويم ام القرى من قائمة نوع التقويم من شاشة ضبط اللغة و التاريح",
	Date_format_validate_error : "الرجاء اختيار تاريخ صحيح",

	senderDate_err : "حدث خطأ بسبب عدم ادخال تاريخ التصدير",
	senderNumber_err : "حدث خطأ بسبب عدم ادخال رقم صادر الجهة المرسلة",

	SourceIncomingcorrespondenceUmmAlQuraDateIsNotSelected : "حدث خطأ بسبب عدم ادخال تاريخ المعاملة الواردة من الجهة الموردة",
	Incomming_From_Is_Empty : "لم يتم اختيار الجهة الموردة للعاملة من القائمة",
	Incomming_Forward_to_Is_Empty : "لم يتم اختيار الجهة المحولة لها المعاملة",

	CompoBoxc_correspondenceSender_Is_Empty : "لم يتم اختيار الجهة المرسلة ",
	CompoBox_commTopTypesId_Is_Empty : "لم يتم اختيار تصنيف الموضوع",
	CompoBox_commTopicSourceId_Is_Empty : "لم يتم اختيار الجهة المصدرة",

	forward_to_outgoing_Is_Missing : "حدث خطأ بسبب عدم  اختيار اسم الجهة الموجهة لها المعاملة",
	Prepared_Departmenet_Is_Missing : "حدث خطأ بسبب عدم  اختيار اسم الجهة المعدة لخطاب الصادرt",
	DeliveryReportNoLable : "رقم بيان التسليم",
	Normal : "عادية",
	Secret : "سري",
	top_secret : "سري جدا",
	extremely_confidential : "سري للغاية",
	Physical_Attachmenet_type : "نوع المشفوعات ",
	Quantity : "الكمية",
	Comments : "الملاحظات",
	No : "الرقم",
	Physical_Attachmenet : "المشفوعات",
	Physical_Attachmenet_Add : "اضافة المشفوعات",
	test_messsage_error : "لا يمكنك تحديد المستخدمين أو المجموعات التي يتوافر لديها امكانية توصل لسطح المكتب هذا.",
	test_messsage_error_explanation : "لا يتوافر لديك التصاريح المناسبة لاسترجاع معلومات المستخدم والمجموعة.",
	test_messsage_error_userResponse : "قم ببدء الاتصال باستخدام اسم مستخدم مختلف أو أطلب من موجه نظام IBM Content Manager منحك امتياز UserACLOwner، المطلوب لاسترجاع معلومات المستخدم والمجموعة.",
	To_Date_Has_not_selected : "لم يتم اختيار تاريخ انتهاء المتابعة",
	From_Date_Has_not_selected : "لم يتم اختيار تاريخ بدء المتابعة",
	error_item_is_exist : "تم اضافته سابقا",

	correspondence_no_label : "رقم المعاملة",

	Decision_correspondence_no_label : "رقم القرار",
	Decision_correspondence_date_label : "تاريخ القرار",
	Decision_correspondence_type_label : "نوع القرار",
	Decision_correspondence_category_label : "تصنيف القرار",

	Circulate_correspondence_no_label : "رقم التعميم",
	Circulate_correspondence_date_label : "تاريخ التعميم",
	Circulate_correspondence_type_label : "نوع التعميم",
	Circulate_correspondence_category_label : "تصنيف التعميم",

	correspondence_date_label : "تاريخ المعاملة",
	Source_Outgoing_correspondence_date_label : "تاريخ صادر الجهة",
	correspondence_type_label : "نوع المعاملة",
	correspondence_category_label : "تصنيف المعاملة",
	confidentiality_label : "السرية",
	prepared_by_label : "الجهة المعدة للخطاب",
	created_by_label : "أنشأت بواسطة",
	mobile_number : "رقم الجوال",
	send_by_label : "صدرت بواسطة",
	physical_attachments_label : "المشفوعات",
	referenced_correspondence_label : "المعاملات المشار إليها",
	remarks_label : "المــــــــــــلاحظات",
	exported_to_label : "صدرت الى",
	incoming_correspondence_information_label : "معلومات المعاملة الواردة",
	Technical_correspondence_information_label : "معلومات المعاملة الفنية",
	internal_correspondence_information_label : "معلومات المعاملة الداخلية",
	circulate_correspondence_information_label : "معلومات التعميم",
	decision_correspondence_information_label : "معلومات القرار",
	outgoing_correspondence_information_label : "معلومات المعاملة الصادرة",
	outgoing_correspondenceSHL_information_label : "معلومات المعاملة الصادرة الى نظام سهل",
	attachments_label : "المرفقات",
	action_label : "الإجراء",
	process_attachments : "الملحقات",
	Lunch_Correspondence : "ارسال",
	Save_Correspondence : "حفظ",
	Save_End_Correspondence : "حفظ وانهاء",
	Process_Correspondence : "اتمام",
	Sign_Compelete : "حفظ بالتوقيع",
	Sign_preview : "معاينة التوقيع",
	Electronic_Attachments : "المرفقات الإلكترونية",
	FilteringSelect_placeholder : "اختر او ادخل احرف",
	FilteringSObserver_placeholder : "اختر المراقب",
	created_by_placeholder : "Select who create it ",
	correspondence_date_placeholder : "اختر التاريخ",
	correspondence_type_placeholder : "to select the type of this correspondence from the list",
	correspondence_category_placeholder : "to slect the category of this correspondence from the list",
	confidentiality_placeholder : "to slect the confidentiality of this correspondence from the list",
	prepared_by_placeholder : "to slect who prepare this correspondence from the list",
	Decision_label : " الاجراء",
	Priority_label : "الاولوية",
	Normal_option : "عادي",
	Urgent_option : "عاجل",
	TopUrgent_option : "عاجل جدا",
    NOW_OPTION : "حالا",
	Deadline_label : "آخر موعد للتنفيذ",
	SetDeadlineAfter_label : "تحديد آخر موعد ",
	Reminder_label : "رسالة التذكير",
	SetReminderafter_label : "رسالة تذكير للمرسل",
	MAH_SetReminderafter_label : "رسالة تذكير للمستلم",
	SetReminderSms_label : "رسالة جوال",
	SetReminderEmail_label : "رسالة بريد إلكتروني",
	Followup_label : "المتابعة",
	From_label : "من",
	followupto_label : "الى",
	Important_CheckBox : "هام",
	RequestReadResponse_checkbox : "إشعار قراءة إلكتروني",
	RequestReadResponseMobile_checkbox : "اشعار قراءة برسالة جوال",
	Orgnication_Structure_per_Permissions_you_have_label : "الهيكل التنظيمي بحسب الصلاحيات",
	Orgnization_All_Structure_Tab : "جميع الأقسام",
	Employees_of_the_Selected_Departmenet : "قائمة الموظفين بحسب الادارة ",
	Forward_To_Emloyees : "احالة الى",
	Cc_to_Emloyees : "ارسال صورة",
	Cc : "صورة",
	TO : "الى",
	to_both_Types : "النوعين",
	Observer : "المراقب",
	Observer_Followup_Correspondence : "تعيين مراقب او  متابع للمعاملة",
	Instruction_to : "توجيهات الى  :  ",
	Draft_Instructions : "توجيهات معرفة سابقا :  ",
	Predefined_Select_Instructions : "اختيار",
	Predefined_Manage_Instructions : "ادارة التوجيهات",
	Edit_Instructions : "تحرير نص التوجيهات",
	Add : "اضافة",
	Remove : "ازالة",
	User_ID : "كود المستخدم",
	User_Name : "اسم المستخدم",
	Dept_Name : "الادارة",
	Instruction : "التوجيهات",
	Forwarding_Type : "نوع الارسال",
	userId : "اسم المستخدم",
	employeeId : "رمز الموظف",
	nationalNumber : "الرقم الوطني",
	fullName : "رمز المستخدم في الدليل النشط",
	departmentId : "رمز الادارة",
	departmentName : "اسم الادارة",
	managerId : "رمز المدير المباشر",
	managerName : "مدير الادارة",
	MANAGER_FULL_NAME_AR : "مدير الادارة",
	parentDepartmentId : "رمز الادارة العليا",
	jobTitle : "المسمى الوظيفي",
	isActive : "هل نشط؟",
	emp_Email : "البريد الاكتروني",
	emp_Mobile : "رقم الجوال",
	specfialization : "التخصص",
	qualification : "المؤهل العلمي",
	degree : "الدرجة الوظيفية",
	enabledOptionsMask : "خيارات الامنية الممنوحة",
	departmentCode : "كود الادارات",
	forwaringToListType : "Forwarding To List Type",
	backupEmployee : "الموظف البديل",
	backupEMPFullName : "اسم الموظف البديل",
	backupUserid : "رمز الموظف البديل",
	backupStartDate : "تاريخ البداية",
	backupEndDate : "تاريخ الانتهاء",
	queueName : "رمز الصندوق المشترك للادارة",
	Has_backupEmployee : "هل يوجد بديل",

	managerUserId : "رمز المدير المباشر",
	managerFullName : "مدير الادارة",
	representativeFullName : "ممثل الادارة",
	departmentLevel : "مستوى الادارة (نوعها)",
	departmentQueueName_English_Lable : "الصندوق المشترك العام ( الاسم الانجليزي)",
	departmentQueueName_Arabic_Lable : "الصندوق المشترك العام ( الاسم العربي)",
	QueueNameCodeLable : "رمز الصندوق المشترك",
	DepartmentTab_Information : "معلومات الادارة",
	Employees_of_the_Selected_Departmenet : "المتاح من موظفين الادارة",
	Grant_Permision : "تحديد",
	Inbasket_Members : "تحديد أعضاء للصندوق العام",
	ApplicationSpaces_Lable : "مكان  التطبيق",
	RolesName_English_Lable : "وظيفة العملية (الاسم الانجليزي)",
	RolesName_Arabic_Lable : "وظيفة العملية (الاسم العربي)",
	ROLE_Text : "وظيفة لـ",
	WorkQueues_Lable : "قوائم انتظار العمل",
	enable_Shared_Inbasket_lable : "تفعيل الصندوق المشترك للادارة",
	Shared_Inbasket : "الصندوق المشترك للادارة",
	COMMITTEEID : "رمز اللجنة",
	COMMITTEENAME : "اسم اللجنة",
	VARIABLENAME : "إسم المتغير",
	VARIABLEVALUE : "قيمة المتغير",
	VARIABLEDESC : "وصف المتغير",
	STARTDATE : "تاريخ البدء",
	ENDDATE : "تاريخ الانتهاء",
	PRESIDENTID : "رمز الرئيس",
	PRESIDENTNAME : "رئيس اللجنة",
	EmployeeName : "اسم الموظف",
	EmployeeList : "قائمة الموظفين",
	Actions_for_Internal_Correspondence : "اجراءات المعاملة الداخلية",
	Actions_for_Circular_Correspondence : "اجراءات معاملة التعميم",
	Actions_for_Decision_Correspondence : "اجراءات معاملة القرار",

	Actions_for_Technical_Correspondence : "اجراءات المعاملة الفنية",
	Instructions_for_Technical_Correspondence : "توجيهات لمستخدمين المعاملة الفنية",

	Instructions_for_Internal_Correspondence : "توجيهات لمستخدمين المعاملة الداخلية",
	Instructions_for_Circular_Correspondence : "توجيهات لمستخدمين التعميم",
	Instructions_for_Decision_Correspondence : "توجيهات لمستخدمين القرارات",

	Actions_for_Incoming_Correspondence : "اجراءات معاملة الوارد الخارجي",
	Actions_for_Outgoing_Correspondence : "اجراءات معاملة الصادر الخارجي",

	Instructions_for_Incoming_Correspondence : "توجيهات لمستخدمين معاملة الوارد",
	Instructions_for_Outgoing_Correspondence : "توجيهات لمستخدمين معاملة الصادر",

	InstructionsToSpecficUsers_option : "لمستخدمين محددين من القائمة",
	InstructionsToAllUsers_option : "لجميع المستخدمين",
	Specfy_Instructions_to_Forwarded_Emloyees : "تخصيص التوجيه لمستلم المعاملة",
	Specfy_Instructions_to_Cced_Emloyees : "تخصيص التوجيه لمستلم صورة من المعاملة ",
	codeTitle : "الرمز",
	IncludeTitle : "يحتوي",
	Currepondance_is_created : "تم حفظ المعاملة بنجاح",
	Currepondance_is_updated : "تم بنجاح تعديل المعاملة ",
	Deadline_time_Type_is_Empty : "نوع المهلة المحددة لم يختار",
	Deadline_time_Number_is_Empty : "وقت المهلة المحددة لم يحدد",
	Enter_Currrespondance_Subject : "لم يتم ادخال موضوع المعاملة بشكل صحيح",
	Enter_Source_Outgoing_Correspondence_No :"لم يتم ادخال رقم جهة الصادر الخارجى بشكل صحيح",
	Enter_Sender_Mobile_Number : "لم يتم ادخال رقم الجوال",
	Reminder_TIme_Type_is_Empty : "نوع موعد التذكير غير محدد",
	Reminder_Time_Number_is_Empty : "موعد موعد التذكير غير مدخل",
	Already_Security_is_applied_for_this_correspondence : "تم بالسابق تطبيق الأمن لهذه المعاملة",
	Security_Successfully_Applied_on_correspondence : "تم بنجاح تطبيق الأمن على المعاملة",
	you_have_already_added_this_Please_select_different_physical_attachment : "تم بالسابق, يمكنك اختيار انواع اخرى من المشفوعات ",
	you_have_already_added_this_Please_select_different_Destination : "الجهة المختارة تم اختيارها مسبقا",
	Select_To_Users : "يجب تحديد عنصر او اكثر من (المستخدمين او من الادارات او كلاهما) المراد  ارسال المعاملة له",
	Select_Cc_Users : "يجب تحديد عنصر او اكثر من (المستخدمين او من الادارات او كلاهما) المراد  ارسال نسخة من المعاملة له",
	HIS_FROM : "من",
	HIS_TO : "الى",
	HIS_CC : "صورة",
	HIS_TIME : "وقت الاجراء",
	HIS_ACTIONS : "الاجراء",
	HIS_IMP : "مهم",
	HIS_CONF : "سري",
	HIS_URG : "عاجل",
	HIS_TOP_URG : "عاجل جدا",
	HIS_REMARKS : "ملاحظات",
	History_label : "شاشة الاحالات",
	add_document_scan_label : "\u0645\u0633\u062d \u0636\u0648\u0626\u0649",
	add_document_scan_button : "مسح ضوئي",
	add_document_scan_entery_label : "مسح ضوئي لوثيقة باستخدام قالب إدخال",
	Outgoing_Forward_to : "تصدير الى",
	Request_Printing_Gregorian_Date_in_BarCode_Label : "طباعة التاريخ الميلادي في الباركود",
	Request_Printing_Statement_delivery : "طباعة بيان التسليم",
	Create_Printing_Statement_delivery : "إنشاء و طباعة بيان التسليم",
	Internal_Label : "داخلي رقم",
	Decision_label_No : "قرار رقم",

	Internal_Date_Lable : "تاريخه",
	Circular_Date_Lable : "ناريخ التعميم",
	CIRCULAR_Label : "تعميم رقم",
	Incoming_Label : "وارد رقم",
	Technical_Label : "معاملة فنية رقم",
	Incoming_No : "رقم الوارد",
	Incoming_Date_Lable : "تاريخه",
	Technical_Date_Lable : "تاريخها",
	Decision_Date_Lable : "تاريخ القرار",
	Outgoing_Label : "صادر رقم",
	Outgoing_Date_Lable : "تاريخه",
	export_by_label : "تصدير من",
	Details : "التفاصيل",
	recieved_on_date : "استلمت بتاريخ",
	added_on_date : "سجلت بتاريخ",
	correspondent_Courier_Name : "اسم المراسل",
	//Source_Outgoing_Correspondence_Number_label : "رقم صادر الجهة\ القيد",
	Source_Outgoing_Correspondence_Number_label : "رقم جهة الصادر الخارجى",
	Source_Outgoing_correspondence_date_label : "تاريخ صادر الجهة",
	Source_Incomming_From : "واردة من",
	Forward_to_departmenet : "موجهة الى",
	Receipt_Way : "طريقة الاستلام",
	Sender_Deatils : "تفاصيل صاحب المعاملة",
	Sender_MobileNumber : "رقم الهاتف",
	Sender_email : "البريد الالكتروني",
	Commerce_Record : "السجل التجاري",
	Civil_Record : "السجل المدني",
	SHOW_OUTGOING_MAPPING : "استدعاء وربط مع معاملات اخرى",
	SHOW_INCOMING_MAPPING : "استدعاء معاملة وارد عام",
	SEARCH_CORRES_HIJRIC_YEAR : "السنة الهجرية",
	SEARCH_CORRES_NUMBER : "رقم المعاملة",
	CALL : "استدعاء",
	btnClear : "مسح",
	btnNew : "جديد",
	btnOK : "موافق",
	SEARCH_CORRES_TYPE : "نوع المعاملة",
	TASDIED_INCOMING : "تسديد معاملة وارد",
	TASDIED_OUTGOING : "تسديد معاملة صادر",
	TASDIED_INTERNAL : "تسديد معاملة داخلية",
	CALL_OUTGOING : "استدعاء/ ربط مع معاملة صادرة",
	MAPPING : "ربط",
	RELATION_TYPE_NEW : "جديد",
	RELATION_TYPE_REPLY : "تسديد",
	RELATION_TYPE_FOLLOWUP : "تعقيب",
	RELATION_TYPE_ADDITION : "إلحاقي",
	RELATION_TYPE_EXPORT : "تصدير",
	RELATIONS : "ربط المعاملات",

	Open_Related_Correspondance : "عرض المعاملة المرتبطة",
	REM_NO : "الرقم",
	SEARCH_CORRES_NUMBER : "رقم المعاملة",
	SEARCH_CORRES_HIJRIC_YEAR : "السنة الهجرية",
	RELATION_TYPE : "جديد",
	RELATION_CORRES_TYPE : "نوع المعاملة",
	DragDrop_Title : "السحب والإسقاط",
	submit_dragdrop : "اضافة",
	dragdrop_setIntroText : " التسلسل الأساسي التي ينطوي عليها عملية السحب والإسقاط هو: تحريك المؤشر إلى ملف او مجموعة من الملفات و من ثم الضغط باستمرار على زر الايمن للماوس لسحب  (الصور) إلى الموقع المطلوب عن طريق تحريك المؤشر و إسقاطها عن طريق تحرير زر و من ثم النقر فوق إضافة إلى اضافة الصور كمرفقات للمعاملة ",
	Subject_ID : "الرمز",
	SubjectNeedToModfied : "قائمة الموضوعات",
	Subject_New_Text : "إضافة نص الموضوع الجديد",
	Manage_Subjects : "تحرير المواضيع",
	SubjectList : "قائمة المواضيع",
	Subject : "الموضوع",
	Update : "تعديل",
	Delete : "حذف",
	Subject_Text : "نص الموضوع",
	Manage_Instruction : "ادارة التوجيهات",
	For_Adding_New_Instruction : "إضافة توجيه جديد",
	for_Updating_New_Instruction : "لتعديل نص التوجيه",
	ManageInstructions : "ادارة التوجيهات",
	predefinedInstruction : "نص التوجيه",
	Instruction_List : "قائمة التوجيهات",
	ManageCorrInst : "إدارة المراسلات الموضوع",
	predefinedCorrInstruction : "معرفة مسبقا المراسلات",
	CorrInstruction_List : "قائمة المراسلات",
	ChangeSubject : "تغيير العنوان",
	NewSUbject : "الموضوع الجديد",
	Edit_Security : "تحرير السرية",
	Viewer : "مشاهد",
	Author : "مؤلف",
	Viewer_User_list : "قائمة المشاهدين",
	Author_User_list : "قائمة المؤلفين",
	Outgoing_No : "رقم الصادر",
	OutgoingLabelNo : "صادر رقم",
	new_internal : "معاملة داخلية",
	new_incoming : "إنشاء وارد",
	new_outgoing : "إنشاء صادر",
	new_decision : "إنشاء قرار",
	new_circulate : "إنشاء تعميم",

	Pick_background_color_for_normal_work_items : "اختيار مؤشر لون الخاص باولوية المعاملات العادية",
	Pick_background_color_for_Urgent_work_items : "اختيار مؤشر لون الخاص  باولوية المعاملات العاجلة",
	Pick_background_color_for_Top_Urgent_work_items : "اختيار مؤشر لون الخاص  باولوية المعاملات العاجلة جدا",

	Inbox_Settings : "اعدادات مؤشر اللون الخاص باولوية المعاملات في صندوق البريد ",

	MoamalatWelcomeMessage : "مرحبا بك في نظام الاتصالات الادارية ~ معاملات",

	Out_Of_Office_With_Delegate_setIntroText : "للإشارة إلى أنك خارج المكتب في تاريخ محدد مع إمكانية تفويض او تكليف موظف آخر لتلقي عملك في الفترة التي ستكون خارج المكتب. و عند العودة إلى المكتب قبل التاريخ المحدد، يجب عليك مسح هذا الإعداد لاستئناف تلقي العمل. حيث  الموظف المكلف سيستمر في  تلقي عملك لحين مسح الإعداد،.",
	Out_Of_Office_With_Delegate : "خارج مكتب / تفويض لموظف آخر",
	Delegaing : "تفويض الى",
	Save : "تخزين",

	StopDelegating : " إيقاف التفويض",
	StartDelegating : " تفعيل التفويض",

	AreYouShureTo_Cancel_Delegation : "هل انت متأكد من ايقاف التفويض و العودة الى المكتب",
	ConfirmationTitle_Cancel_Delegation : "التأكيد على العودة الى المكتب",
	OK_to_Cancel_Delegating_Button_Desc : "التأكيد",
	Cancelof_Cancel_Delegating_Button_Desc : "لا",

	AreYouShureTo_Delegate_your_Work : "هل انت متأكد من تفعيل التفويض و الخروج من المكتب ",
	ConfirmationTitle_Enable_Delegation : "التأكيد على الخروج من المكتب",
	OK_on_Delegating_Button_Desc : "التأكيد",
	Cancelof_Delegating_Button_Desc : "لا",

	Account_No_label : "رقم الحساب",

	CIF_NO : "رقم حساب العميل",
	BRANCH : "الفرع",
	FIRST_NAME : "الاسم الاول",
	LAST_NAME : "العائلة",
	NATIONALITY : "الجنسية",
	ID_TYPE : "نوع الهوية",
	ID_NUMBER : "رقم الهوية",
	ACCOUNT_NO : "رقم الحساب",
	ID_DATE : "تاريخ الهوية",
	Lunch_Process : "ارسال",
	StepProcessor_Fawri_Workflow : "متابعة عمل  مسار الفوري",
	StepProcessor_StepProcessor_Fawri_Workflow_setIntroText : "لاختيار العملية المطلوبة لاكمال و متابعة عمل  مسار الفوري",

	F_OriginatorDisplayName : "تم البدء بواسطة",
	F_StepName : "الخطوة",

	F_StepReceived : "تم الاستلام في",
	F_Subject : "الموضوع",

	FawriRemark : "الملاحظات",
	Branch_Notes : "ملاحظات موظفين الفرع",
	Branch_Manager_Notes : "ملاحظات مدير الفرع",

	F_Deadline : "تاريخ الاستحقاق",
	Main_Branch_Notes : "ملاحظات عمليات الفرع الرئيسي",
	Main_Branch_Manager_Notes : "ملاحظات مدير عمليات الفرع الرئيسي",
	FawriWelcomeMessage : "مرحبا بك في نظام فوري",

	// tooltip

	HLP_correspondence_subject_label : "نص لوصف محتوى المعاملة",
	HLP_DecisionCorrespondence_subject_label : "نص لوصف محتوى القرار",
	HLP_CirculationCorrespondence_subject_label : "نص لوصف محتوى التعميم",
	HLP_correspondence_no_label : "رقم محجوز للمعاملة (يمكن استخدامه للوصول لها)",
	HLP_Decision_correspondence_no_label : "رقم محجوز للقرار (يمكن استخدامه للوصول له)",
	HLP_Circulation_correspondence_no_label : "رقم محجوز للتعميم (يمكن استخدامه للوصول له)",
	HLP_correspondence_type_label : "نوع المعاملة بحسب هيئتها",
	HLP_Decision_type_label : "نوع القرار بحسب هيئتة",
	HLP_Circulation_type_label : "نوع التعميم بحسب هيئتة",
	HLP_correspondence_date_label : "تاريخ إنشاء المعاملة (يمكن استخدامه للوصول لها)",
	HLP_Decision_correspondence_date_label : "تاريخ إنشاء القرار (يمكن استخدامه للوصول له)",
	HLP_Circulation_correspondence_date_label : "تاريخ إنشاء التعميم (يمكن استخدامه للوصول له)",
	HLP_correspondence_recieved_on_date : "تاريخ إستلام المعاملة",
	HLP_correspondence_created_by_label : "نص تلقائي ثابت يبين اسم الموظف المنشأة للمعاملة",
	HLP_correspondence_category_label : "تصنيف المعاملة بناء على الهدف والغرض الذى انشأت من اجله",
	HLP_Decision_correspondence_category_label : "تصنيف القرار بناء على الهدف والغرض الذى انشأ من اجله",
	HLP_Circulation_correspondence_category_label : "تصنيف القرار بناء على الهدف والغرض الذى انشأ من اجله",
	HLP_confidentiality_label : "تحديد درجة سرية المعاملة، وذلك لجعلها متاح فقط للجهات التى تملك صلاحية لفتح هذه الدرجة من السرية",
	HLP_Decisionconfidentiality_label : "تحديد درجة سرية القرار، وذلك لجعله متاح فقط للجهات التى تملك صلاحية لفتح هذه الدرجة من السرية",
	HLP_Circulationconfidentiality_label : "تحديد درجة سرية التعميم، وذلك لجعله متاح فقط للجهات التى تملك صلاحية لفتح هذه الدرجة من السرية",
	HLP_prepared_by_label : "نص تلقائي ثابت يبين اسم الادارة المنشأة للمعاملة",
	HLP_Decisionprepared_by_label : "نص تلقائي ثابت يبين اسم الادارة المنشأة للقرار",
	HLP_Circulationprepared_by_label : "نص تلقائي ثابت يبين اسم الادارة المنشأة للتعميم",
	HLP_physical_attachments_label : "مرفقات عينية (مثل: الاقراص المدمجة، كتاب...)",
	HLP_created_by_label : "نص تلقائي ثابت يبين اسم الموظف المنشأ للمعاملة",
	HLP_Decisioncreated_by_label : "نص تلقائي ثابت يبين اسم الموظف المنشأ للقرار",
	HLP_Circulationcreated_by_label : "نص تلقائي ثابت يبين اسم الموظف المنشأ للتعميم",
	HLP_remarks_label : "مساحة نصية لاضافة ملاحظات حول المعاملة",
	HLP_Decisionremarks_label : "مساحة نصية لاضافة ملاحظات حول القرار",
	HLP_Circulationremarks_label : "مساحة نصية لاضافة ملاحظات حول التعميم",
	HLP_correspondent_Courier_Name : "إسم المراسل الذى احضر المعاملة",
	HLP_Subject_New_Text : "إضافة موضوع معاملة جديد",
	HLP_For_Adding_New_Instruction : "إضافة موضوع توجيه جديد",
	HLP_Instruction_List : "عمل تعديل على موضوع توجيه مُعرف مسبقاً",
	HLP_SubjectNeedToModfied : "عمل تعديل على موضوع معاملة مُعرف مسبقاً",
	HLP_DeliveryReportNoLable : "رقم بيان تسليم المعاملة",
	HLP_Decision_label : "تحديد نوع الإجراء على المعاملة",
	HLP_DecisionDecision_label : "تحديد نوع الإجراء على القرار",
	HLP_CirculationDecision_label : "تحديد نوع الإجراء على التعميم",
	HLP_SetReminderafter_label : "تنبيه خاص بالمعاملة للتذكير بها في حالة عدم العمل عليها",
	HLP_Followup_label : "متابعة المعاملة منذ احالتها لاول جهة معنية عن طريق التاريخ",
	HLP_DecisionFollowup_label : "متابعة القرار منذ احالته لاول جهة معنية عن طريق التاريخ",
	HLP_CirculationFollowup_label : "متابعة التعميم منذ احالتها لاول جهة معنية عن طريق التاريخ",
	HLP_Priority_label : "تحديد درجة اهمية المعاملة",
	HLP_DecisionPriority_label : "تحديد درجة اهمية القرار",
	HLP_CirculationPriority_label : "تحديد درجة اهمية التعميم",
	HLP_SetDeadlineAfter_label : "وقت محدد لانهاء العمل على المعاملة",
	HLP_RequestReadResponse_label : "تنبيه عند استلام المعاملة للجهة المعنية",
	HLP_DecisionRequestReadResponse_label : "تنبيه عند استلام القرار للجهة المعنية",
	HLP_CirculationReadResponse_label : "تنبيه عند استلام التعميم للجهة المعنية",
	HLP_Important_CheckBox : "تنبيه باهمية المعاملة",
	HLP_DecisionImportant_CheckBox : "تنبيه باهمية المعاملة",
	HLP_CirculationImportant_CheckBox : "تنبيه باهمية المعاملة",
	HLP_Source_Outgoing_correspondence_date_label : "تاريخ صدور المعاملة (يمكن استخدامه للوصول لها)",
	HLP_Source_Outgoing_Correspondence_Number_label : "رقم المعاملة من الجهة الموردة",
	HLP_Source_Incomming_From : "الجهة المصدرة للمعاملة الى الداخل",
	HLP_Civil_Record : "السجل المدني",
	HLP_Sender_MobileNumber : "رقم جوال المعني بالمعاملة",
	HLP_Receipt_Way : "الطريقة او الوسيلة التى تم استلام المعاملة ابها",
	HLP_Sender_Deatils : "نص بتفاصيل اكثر عن المعني بالمعاملة",
	HLP_Commerce_Record : "رقم السجل التجاري",
	HLP_Sender_email : "نص يستخدم لادخال رقم البريد للجهة المعنية",
	HLP_Forward_to_departmenet : "الجهة الموجه لها المعاملة وتكون داخلية",
	HLP_Create_Printing_Statement_delivery : "ملف بيبن بان المعاملة استلمت، يكون مرفق معها",
	HLP_letterType : "نوعية المعاملة",
	HLP_Details : "نص تفصيلي بمحتوى المعاملة",
	HLP_SentVia : "وسيلة ارسال المعاملة",
	HLP_export_by_label : "نص تلقائي ثابت يبين اسم الموظف المنشأ للمعاملة",
	HLP_Request_Printing_Gregorian_Date_in_BarCode_Label : "ظهور التاريخ الميلاد في الباركود",
	HLP_SHOW_INCOMING_MAPPING : "إستدعاء معاملة وعرض بياناتها",
	HLP_SEARCH_CORRES_HIJRIC_YEAR : "تاريخ إنشاء المعاملة ( يمكن استخدامه للوصول لها)",
	HLP_added_on_date : "تاريخ تسجيل المعاملة",
	HLP_Subject_Text : "اكتب موضوع المعاملة الجديد",
	HLP_Edit_Instructions : "تحرير نص التوجيهات",
	HLP_withatachmnet : "إستدعاء مرفقات المعاملة معها",
	HLP_exported_to_label : "الجهة التى تم تصدير المعاملة إليها",

	HLP_codeTitle : "يتم كتابة رقم الادارة لتظهر بالقائمة المنسدلة",
	HLP_IncludeTitle : " تظهر جميع الادارات بالقائمة بمجرد كتابة بعض الحروف من اسم الادارة",
	HLP_Instruction_to : "توجيه توجيهات للموظفين او مستلمين المعاملة ",
	HLP_DecisionInstruction_to : "توجيه توجيهات للموظفين او مستلمين القرار ",
	HLP_CirculationInstruction_to : "توجيه توجيهات للموظفين او مستلمين التعميم ",
	HLP_Draft_Instructions : "قائمة تحتوى جميع التوجيهات المعرفة سابقاً",
	HLP_Manage_Instruction : "عمل تعديل على التوجيهات المختارة من قائمة التوجيهات المعرفة سابقاً",
	HLP_Observer : "اختيار موظف يقوم بتتبع مسار المعاملة",
	HLP_DecisionObserver : "اختيار موظف يقوم بتتبع مسار القرار",
	HLP_CirculationObserver : "اختيار موظف يقوم بتتبع مسار التعميم",
	HLP_DestinationName : "اسم الجهة المصدرة لها المعاملة الى الخارج",
	HLP_Label_Attachments : "ملف يرفق مع المعاملة",
	HLP_Label_Export_Attachments : "وصف مرفقات المعاملة",
	HLP_Physical_Attachmenet_type : "نوع المشفوعات او المرفقات العينية مع المعاملة",
	HLP_Quantity : "عدد المرفقات العينية",
	HLP_Comments : "مساحة نصية يكتب فيها ملاحظات عن المرفقات العينية",

	// Admin mahmoud hegazy
	// Manage Employees
	HLP_fullNameLable : "نص لاضافة او البحث عن موظف معين",
	HLP_emp_EmailLable : "بريد الكتروني خاص بموظف معين",
	HLP_nationalNumberLable : "رقم الهوية للموظف ",
	HLP_departmentIdLable : "قائمة لاضافة او البحث عن ادارة معينة",
	HLP_emp_MobileLable : "رقم الجوال للموظف ",
	HLP_managerIdLable : "نص يظهر مدير الادارة المختارة",
	HLP_degreeLable : "الترتيب الوظيفي للموظف في المنظمة",
	HLP_specfializationLable : "المهام المناطة للموظف",
	HLP_userIdLable : "رمز لتسجيل دخول الموظف الى النظام ",
	HLP_jobTitleLable : "اسم الوظيفة الذي يقوم بها الموظف",
	HLP_employeeIdLable : "رمز محجوز مختصر للموظف ",
	HLP_isActiveLable : "هل الموظف على راس عملة ",
	HLP_qualificationLable : "مسمى الشهادة الجامعية او غيرها للموظف ",
	HLP_RIGHT_SCAN_BLACK_Lable : "Print the document using the black color",
	HLP_RIGHT_SCAN_GRAY_Lable : "صلاحية تُعطى للموظف المعني لاستخدام الماسح الضوئي الرمادي",
	HLP_RIGHT_SCAN_COLOR_Lable : "صلاحية تُعطى للموظف المعني لاستخدام الماسح الضوئي الملون",
	HLP_RIGHT_SEND_OUTGOING_WITH_OLD_DATE_Lable : "Send correspondence in the old date",
	HLP_RIGHT_CREATE_GENERALIZATIONS_Lable : "صلاحية تُعطى للموظفين المعنيين لمخاطبة جميع الموظفين ( صلاحية خاصة بالمدراء).",
	HLP_RIGHT_SEND_WITHOUT_ATTACHMENTS_Lable : "صلاحية الارسال المحدد للوارد والصادر بدون مرفقات وتُحدد لبعض الموظفين المعنيين بذالك",
	HLP_RIGHT_CREATE_STATISTICAL_REPORTS_Lable : "صلاحية لإنشاء التقارير الاحصائية (تُحدد لبعض الموظفين الذين لديهم صلاحية لذالك)",
	HLP_RIGHT_FOLLOWUP_REMINDER_Lable : "صلاحية تُعطى لبعض الموظفين المعنيين بالتذكير بمتابعة المعاملة",
	HLP_RIGHT_DEPT_SEARCH_OPTION_Lable : "صلاحية الوصول لمعاملات الادارة باكملها وتحدد لبعض الموظفين المعنيين بذالك",
	HLP_RIGHT_MAIN_DEPARTMENT_MANAGER_Lable : "The validity of the agency director",
	HLP_RIGHT_EDIT_OUTGOING_Lable : "صلاحية تُعطى للتعديل على معاملات الصادر الخارجي تُحدد لبعض الموظفين المعنيين بذالك",
	HLP_RIGHT_EDIT_INCOMING_Lable : "صلاحية تعطى للتعديل على معاملات الوارد الخارجي تحدد لبعض الموظفين المعنيين بذالك",
	HLP_RIGHT_EDIT_INTERNAL_Lable : "Editing for internal correspondences",
	HLP_RIGHT_FULL_SEARCH_OPTION_Lable : "صلاحية الوصول لمعاملات الوزارة باكملها وتُحدد لبعض الموظفين المعنيين بذالك",
	HLP_RIGHT_MANAGER_PERMISSION_Lable : "صلاحية تعطى لمدير محدد للادارة في المراسلات ",
	HLP_RIGHT_SHOW_CONFIDENTIALITY_SECURE_Lable : "Manager special to view secure correspondence  ",
	HLP_RIGHT_SHOW_CONFIDENTIALITY_VERY_SECURE_Lable : "صلاحية تُعطى لبعض المدراء والموظفين للاطلاع على المعاملات السرية جدا",
	HLP_RIGHT_SHOW_CONFIDENTIALITY_EXTREME_SECURE_Lable : "صلاحية تعطى لمدير محدد للادارة في المراسلات ",
	HLP_RIGHT_COMMUNICATE_ALL_EMPLOYEE_Lable : "صلاحية تُعطى للموظفين المعنيين لمخاطبة جميع الموظفين ( صلاحية خاصة بالمدراء).",
	HLP_RIGHT_EDIT_CORR_DETAILS_Lable : "صلاحية تُعطى للتعديل على معلومات المعاملة تُحدد للموظفين المعنيين بذالك ",
	HLP_RIGHT_EDIT_CORR_ATTACHMENTS_Lable : "صلاحية تعديل واضافة والغاء مرفقات من معاملات محددة تحدد لبعض الموظفين المعنيين بذالك",
	HLP_RIGHT_EDIT_CORR_RESEND_Lable : "صلاحية اعادة ارسال او تعديل المعاملات",
	HLP_RIGHT_END_CORRESPONDENCE_Lable : "صلاحية الحفظ والانهاء للمعاملة تُعطى للموظفين المعنيين بذالك",
	HLP_RIGHT_DELETE_HISTORY_AND_WORITEMS_Lable : "صلاحية تعطى لموظفيين معنيين بالتحكم في سجل الاحالات والحذف منها جهات مراد حذفها",
	HLP_RIGHT_REMINDER_MESSAGE_Lable : "صلاحية تُعطى للموظف لامكانية اضافة رسالة تذكير",
	HLP_RIGHT_DEADLINE_Lable : "صلاحية تُعطى للموظفين المعنيين لتحديد اخر موعد لانهاء المعاملة ",
	HLP_HasbackupEmployeeLable : "لاختيار الموظف البديل من القائمة ",
	HLP_BackupFromDate : "تاريخ اول يوم عمل للموظف البديل ",
	HLP_backupEndDateLable : "تاريخ اخر يوم عمل للموظف البديل",

	// Manage Departments
	HLP_canAccessSystemLable : "ظهور او اخفاء الادارة من النظام",
	HLP_rep_full_nameLable : "اظهار او اضافة نائب مدير الادارة المعنية",
	HLP_manager_full_name_arLable : "اظهار او اضافة مدير ادارة معينة ",
	HLP_departmentNameLable : "اظهار او اضافة ادارة معينة",
	HLP_RIGHT_EXPORT_Lable : "صلاحية لتصدير المعاملات تحدد على مستوى الادارة باكملها",
	HLP_RIGHT_CREATE_OUTGOING_Lable : "صلاحية لإنشاء معاملات صادر خارجي تحدد على مستوى الادارة باكملها",
	HLP_RIGHT_CREATE_INCOMING_Lable : "صلاحية لإنشاء معاملات وارد خارجي تحدد على مستوى الادارة باكملها",
	HLP_RIGHT_CREATE_INTERNAL_Lable : "صلاحية لإنشاء معاملات داخلية تحدد على مستوى الادارة باكملها",
	HLP_RIGHT_Department_Represented_Lable : "صلاحية استلام المعاملات تحدد لممثل الادارة فقط",
	HLP_RIGHT_CREATE_DECESIONS_Lable : "صلاحية تعطى لبعض الموظفين المعنيين بإنشاء القرارات",
	HLP_RIGHT_CREATE_CIRCULARS_Lable : "صلاحية إنشاء تعاميم تحدد على مستوى الادارة باكملها",
	HLP_enable_Shared_Inbasket_lable : "تفعيل او الغاء الادارة التابعة لها الادارة الحالية",
	HLP_departmentQueueNameLable : "رقم محجوز للادارة الحالية",
	HLP_queueNameLable : "الادارة التابعة (الادارة الام)للادارة الحالية",

	// Manage Public Inbasket
	HLP_WorkQueues_Lable : "قائمة لانتظار الاعمال",
	HLP_ApplicationSpaces_Lable : "",
	HLP_queueNameLable : "",
	HLP_RolesName_English_Lable : "",
	HLP_RolesName_Arabic_Lable : "",
	HLP_departmentQueueName_English_Lable : "",
	HLP_departmentQueueName_Arabic_Lable : "",

	// Manage Public Inbasket Members
	HLP_Shared_Inbasket : "لاختيار الصندوق المشترك للادارة الحالية من القائمة",
	HLP_departmentName : "لاختيار الادارة المراد اظهارها بقائمة الاعضاء",
	HLP_EmployeeName : "لاختيار اسم الموظف المراد اظهارة بقائمة الاعضاء",

	// Manage Committees
	HLP_COMMITTEENAME : "لاضافة لجنة محددة اعضائها",
	HLP_PRESIDENTNAME : "اختيار رئيس اللجنة المُحدد من القائمة ",
	HLP_STARTDATE : "تاريخ بداية اعمال اللجنة",
	HLP_ENDDATE : "تاريخ نهاية اعمال اللجنة",

	// Manage Committees Members
	HLP_EmployeeList : "",

	// added by Bashar 15-12-2016

	Show_Orgnization_logo_on_Barcode_Lable : "اظهار شعار المؤسسة على ملصق الباركود",
	Show_Orgnization_logo_on_Enquiry_Ticket : "اظهار شعار المؤسسة على تذكرة المراجعة",
	Show_QR_Code_on_Internal_Correspondence_Barcode_Lable : "اظهار رمز الاستجابة السريعة عند طباعة ملصق الباركود لشاشة المعاملة الداخلية",
	Show_QR_Code_on_Incoming_Correspondence_Barcode_Lable : "اظهار رمز الاستجابة السريعة عند طباعة ملصق الباركود لشاشة المعاملة الواردة",
	Show_QR_Code_on_Outgoing_Correspondence_Barcode_Lable : "اظهار رمز الاستجابة السريعة عند طباعة ملصق الباركود لشاشة المعاملة الصادرة",
	Show_BarCode_Image_on_Internal_Correspondence_Barcode_Lable : "اظهار رمز الباركود عند طباعة ملصق الباركود لشاشة المعاملة الداخلية",
	Show_BarCode_Image_on_Incoming_Correspondence_Barcode_Lable : "اظهار رمز الباركود عند طباعة ملصق الباركود لشاشة المعاملة الواردة",
	Show_BarCode_Image_on_Outgoing_Correspondence_Barcode_Lable : "اظهار رمز الباركود عند طباعة ملصق الباركود لشاشة المعاملة الصادرة",
	Clear_Logo_Image : "مسح الشعار",
	Save_Setting : "تخزين",
	Manage_Barcod_Lable_Images_Settings : "ادارة ملصق الباركود",
	Orgnization_Logo_For_Barcode_Lable : "شعار المؤسسة للملصق الباركود",
	Add_Orgnization_Logo : "اضافة شعار المؤسسة:",
	Show_In_Document : "فعال",

	Manage_Web_Editor_Header_Footer_Images_Settings : "إدارة رأس  و ذيل الوثائق التي سيتم إنشاؤها من محرر ويب المعاملات",
	WebEditor_Image_Type_Lable : "Type",

	WithAttachments : "مع مرفقات المعاملة",
	RELATION_EDIT : "البحث و الربط بمعاملات اخرى",
	Error_EnterFullNameOrFirstCharacterOfHisName : "الرجاء ادخال اسم الموظف  او الاحرف الاولة من اسم الموظف المسجل في الدليل النشط للنظام (اكتيف دايروكتوري)",
	Error_HaveNotFoundSuchUserAccountInLdap : "اسم المستخدم الذي تم ادخاله خطأ او لا يوجد حقل له في الدليل النشط للنظام (اكتيف دايروكتوري)",
	AdminHR_fullNameDB_LBL : "اسم الموظف الكامل",

	HLPAdmin_fullNameDB : "اسم الموظف في قاعدة البيانات",

	error_MessageForAttachmentOfMoamalat : "لا يمكنك ارسال هذه المعاملة من دون مرفق الكتروني على الأقل!",
	Exported : "تم تصديرها",

	error_no_Internal_transfered_workflow_found : "حدث خطأ، لم يتم العثور على مسار العمل خاص باجراء العمل للداخلي",
	error_URL_parameter_for_Outgoing_workClassName_is_missing : "حدث خطأ بسبب فقدان احد اقسام عنوان رابط الاتصال من اجراء العمل للصادر",

	RELATION_TYPE_DECISIONS : "قرار",
	RELATION_TYPE_CIRCULARS : "تعميم",

	error_no_CIRCULARS_transfered_workflow_found : "حدث خطأ، لم يتم العثور على مسار العمل خاص باجراء العمل للتعاميم",
	error_URL_parameter_for_CIRCULARS_workClassName_is_missing : "حدث خطأ بسبب فقدان احد اقسام عنوان رابط الاتصال من اجراء العمل للتعميم",
	error_no_DECISIONS_transfered_workflow_found : "حدث خطأ، لم يتم العثور على مسار العمل خاص باجراء العمل للقرارات",
	error_URL_parameter_for_DECISIONS_workClassName_is_missing : "حدث خطأ بسبب فقدان احد اقسام عنوان رابط الاتصال من اجراء العمل للقرار",

	create_new_internal_correspondence_label : "إنشاء احالة داخلية جديــدة",
	create_new_Registration_correspondence_label : " إنشاء حساب جديد",
	Registration_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في الحسابات",

	internal_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في الاحالات الداخلية لايجاد المعاملة .",
	create_new_circulate_correspondence : "انشـــــاء تعمــــيم جديـــــد",
	circulate_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في التعاميم لايجاد المعاملة .",
	create_new_decision_correspondence : "انشـــــاء قـــــرار جديـــــد",
	create_new_decision_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في القرارات لايجاد المعاملة.",
	create_new_outgoing_correspondence : "إنشاء معاملة صادر جديدة",
	create_new_outgoing_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في المعاملات الصادرة لايجاد المعاملة .",

	View_outgoing_correspondence : "استعراض معاملة صادرة",
	View_outgoing_correspondence_properties_setIntroText : "يمكن الاستفادة من حقول الفهرسة للبحث على المعاملة  الصادرة ",

	View_outgoingSHL_correspondence : "استعراض معاملة صادر خارجي الي نظام سهل",
	View_outgoingSHL_correspondence_properties_setIntroText : "يمكن الاستفادة من حقول الفهرسة للبحث على المعاملة  الصادرة",

	View_Internal_correspondence : "استعراض معاملة داخلية",
	View_Internal_correspondence_properties_setIntroText : "يمكن الاستفادة من حقول الفهرسة للبحث على المعاملة  الداخلية ",
	View_Incoming_correspondence : "استعراض معاملة واردة",
	View_Incoming_correspondence_properties_setIntroText : "يمكن الاستفادة من حقول الفهرسة للبحث على المعاملة  الواردة ",
	View_Circulate_correspondence : "استعراض معاملة تعميم",
	View_Circulate_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في التعاميم الادارية لايجاد المعاملة",
	View_Decision_correspondence : "استعراض معاملة قرار",
	View_Decision_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في القرارات الادارية لايجاد المعاملة",
	StepProcessor_Circulate_correspondence : "متابعة مسار عمل معاملة التعميم الاداري",
	StepProcessor_Circulate_correspondence_setIntroText : "يمكنك الاستفادة من القيم التي تم ادخالها في البحث عن  معاملات التعماميم الادارية لايجادها",
	StepProcessor_Decision_correspondence : "متابعة مسار عمل معاملة القرار الاداري",
	StepProcessor_Decision_correspondence_setIntroText : "يمكنك الاستفادة من القيم التي تم ادخالها في البحث عن  معاملات القرارات الادارية لايجادها",
	create_new_incoming_correspondence : "إنشاء معاملة وارد جديــدة",
	create_new_incoming_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في المعاملات الواردة  لايجاد المعاملة.",

	create_new_Technical_correspondence : "إنشاء معاملة فنية جديدة",
	create_new_Technical_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في المعاملات الفنية  لايجاد المعاملة.",

	stepProcessor_unified_actions_on_set_of_Correspondence : "اجراء موحد على مجموعة من المعاملات",
	stepProcessor_unified_actions_on_set_of_Correspondence_setIntroText : "هذه الخاصية تمكنك من اتخاذ اجراء موحد على مجموعة من المعاملات",

	StepProcessor_internal_correspondence : "متابعة مسار عمل معاملة الاحالة الداخلية",
	StepProcessor_internal_correspondence_setIntroText : "يمكنك الاستفادة من القيم التي تم ادخالها في البحث عن الاحالات الداخلية لايجاد المعاملة",
	StepProcessor_outgoing_correspondence : "متابعة مسار عمل المعاملة الصادرة",
	StepProcessor_outgoing_correspondence_setIntroText : "يمكنك الاستفادة من القيم التي تم ادخالها في البحث عن المعاملة الصادرة لايجادها",
	StepProcessor_incoming_correspondence : "متابعة مسار عمل المعاملة الواردة",
	StepProcessor_incoming_correspondence_setIntroText : "يمكنك الاستفادة من القيم التي تم ادخالها في البحث عن المعاملة الواردة  لايجادها",
	stepProcessor_Technical_Correspondence : "متابعة مسار عمل المعاملة الفنية",
	stepProcessor_Technical_Correspondence_setIntroText : "يمكنك الاستفادة من القيم التي تم ادخالها في البحث عن المعاملة الفنية  لايجادها",

	new_internal_correspondence_label : "الاحالات الداخلية الجديدة",
	new_circulate_correspondence_label : "التعاميم الجديدة",
	new_decision_correspondence_label : "القرارت الجديدة",
	new_outgoing_correspondence_label : "معاملات الصادر الحديدة",
	new_incoming_correspondence_label : "معاملات الوارد الجديدة",
	correspondence_subject_label : "موضوع المعاملة",
	CirculateCorrespondence_subject_label : "موضوع التعميم",
	DecisionCorrespondence_subject_label : "موضوع القرار",

	Outgoing_correspondence_subject_label : "موضوع المعاملة",
	Incoming_correspondence_subject_label : "موضوع المعاملة",
	Technical_correspondence_subject_label : "موضوع المعاملة",

	Viewing_Internal_correspondence : "استعراض المعاملة الداخلية",
	Viewing_Incoming_correspondence : "استعراض المعاملة الواردة",
	Viewing_Circulate_correspondence : "استعراض التعميم",
	Viewing_Decision_correspondence : "استعراض القرار",
	Viewing_outgoing_correspondence : "استعراض المعاملة الصادرة",

	Lunching_Internal_correspondence : "لتعديل و إنجاز المعاملة الداخلية",
	Lunching_Incoming_correspondence : "لتعديل و إنجاز المعاملة الواردة",
	Lunching_Circulate_correspondence : "لتعديل و إنجاز التعميم",
	Lunching_Decision_correspondence : "لتعديل و إنجاز القرار",
	Lunching_outgoing_correspondence : "لتعديل و إنجاز المعاملة الصادرة",

	Editing_Internal_correspondence : "لتعديل المعاملة الداخلية",
	Editing_Incoming_correspondence : "لتعديل المعاملة الواردة",
	Editing_Circulate_correspondence : "لتعديل التعميم",
	Editing_Decision_correspondence : "لتعديل القرار",
	Editing_outgoing_correspondence : "لتعديل المعاملة الصادرة",

	Completing_Internal_correspondence : "لاكمال المعاملة الداخلية",
	Completing_Incoming_correspondence : "اكمال المعاملة الواردة",
	Completing_Circulate_correspondence : "لاكمال التعميم",
	Completing_Decision_correspondence : "لاكمال القرار",
	Completing_outgoing_correspondence : "لاكمال المعاملة الصادرة",

	VIEW_CORRESPONDENCE : "عرض المعاملة",
	EDIT_CORRESPONDENCE : "تعديل المعاملة",
	DETAILS_CORRESPONDENCE : "تتبع المعاملة",
	Lunch_New_CORRESPONDENCE : "إعادة ارسال",
	COmplete_CORRESPONDENCE : "اكمال المعاملة",

	Employees_label : "الموظفين",
	Find_Employees_label : "إبحث عن موظف",
	Search_Label : "إبحث",
	Committee_Description_Label : "وصف اللجنة",
	Update_Logo_Label : "تحديث الشعار",
	Correspondence_Type_Label : "نوع المعاملة",
	Select_Department_Label : "اختار الإدارة",
	Search_By_Label : "بحث ب",
	Employee_Label : "موظف",
	Department_Label : "إدارة",
	Select_Employee_Label : "إختار الموظف",

	All_Departments : "الهيكل الهرمي",
	My_Favorites_list : "قائمتي المفضلة",
	My_Favorites_list_Header : "قائمتي المفضلة",
	Custome_List : "القائمة المعرفة مسبقاً",
	Custome_List_Header : "القائمة المعرفة مسبقاً",
	HLP_SEARCH_CORRES_NUMBER : "البحث برقم المعاملة",

	Add_to_Forward_List : "اضافة الى قائمة ارسال الى الموظف",
	Add_to_Copy_List : " اضافة الى قائمة ارسال صورة للموظف ",
	Add_To_My_Favourite_List : "اضافة الى قائمتي المفضلة",
	Remove_from_My_Favourite_List : "ازالة من قائمتي المفضلة",
	Move_into_Instruction_forward_List : "نقل الى قائمة التوجيهات",
	Move_into_Instruction_Copy_List : " نقل الى قائمة التوجيهات ",
	Remove_from_List : "ازالة من القائمة",

	commTopicSourceId : "الجهة المرسلة",
	senderNumber : "رقم صادر الجهة المرسلة",
	senderDate : "تاريخ التصدير",
	correspondenceSender : "الجهة المصدرة",
	commTopTypesId : "تصنيف الموضوع",

	KeyWord_Is_Missing_err : "على الاقل يجب ادخال  5 كلمات دالة",

	KeyWords : "الكلمات الدلالية",

	View_Technical_correspondence : "استعراض معاملة فنية",
	View_Technical_correspondence_properties_setIntroText : "يمكن الاستفادة من حقول الفهرسة للبحث على المعاملة  الفنية ",
	Completing_Technical_correspondence : "اكمال المعاملة الفنية",

	Lunching_Technical_correspondence : "لتعديل و إنجاز المعاملة الفنية",

	Editing_Technical_correspondence : "لتعديل المعاملة الفنية",

	Technical : "معاملة فنية",
	Show_Attachments : "اظهار قائمة المرفقات",

	employeecolor : "موظف",
	departmentcolor : "ادارة",
	queuecolor : "مجموعة عمل",
	committee_has_not_Selected : "يجب اختيار لجنة على الاقل لاتمام إنشاء معاملة فنية",
	Drag_Drop_Error : "يمكن ااستخدام خاصية السحب و الاسقاط للملفات او الوثائق",
	File_Uploader : "رفع الملفات",
	Drag_and_Drop_files_Here : "سحب و اسقاط الملفات هنا",
	// WebEditor values
	webeditorsettings : "إدارة محرر النصوص",
	manageWebEditorHF : "إدارة ترويسات الملفات",
	manageWebEditorTemplates : "إدارة القوالب ",

	headerName : "إسم الترويسة ",
	repositoryName : "اسم REPOSITORY",
	headerImageName : "رأس الصفحة",
	footerImageName : "ذيل الصفحة",
	defaultHF : "ترويسة اساسية",
	yes : "نعم",
	no : "لا",
	active : "نشط",
	inactive : "غير نشط",
	hNameRequired : "إسم الترويسة إجبارى",
	repositoryNameRequired : "اسم repository اجبارى",
	headerRequired : "لابد من ادخال رأس الصفحة",
	footerRequired : "لابد من ادخال ذيل الصفحة",
	hsaveSuccess : "تم الحفظ بنجاح",
	hsaveFailed : "حدث خطأ فى الحفظ",
	statuslabel : "الحاله",
	contentLabel : "محتويات الترويسة",
	attachmentLabel : "المرفقات",
	dateLabel : "التاريخ",
	numberLabel : "رقم المعاملة",
	subjectLabel : "الموضوع",
	editbuttonLabel : "تعديل",
	addbuttonLabel : "إضافة",
	newLabel : "جديد",
	previewHeaderButton : "عرض صورة رأس الصفحة",
	previewFooterButton : "عرض صورة ذيل الصفحة",

	templateName : "إسم القالب",
	templateUserName : "إسم المستخدم",
	userNameLabel : "إختر اسم المستخدم",
	headerNameLabel : "إختر اسم الترويسة",
	usernameLabelfilter : "إختر اسم المستخدم للتصفية",
	templateaddButton : "إضافة",
	templateeditButton : "تعديل",
	templatenewButton : "جديد",
	templateNameRequired : "لابد من إدخال إسم القالب",
	templateContent : "لابد من ادخال محتوى القالب",
	auditTrail : "العمليات على النظام",
	auditTrailReport : " تقرير العمليات",
	operationNameLabel : "إسم العمليه",
	auditUserName : "إسم المستخدم",
	auditFromDate : "من تاريخ",
	auditToDate : "إلى تاريخ",
	auditCorrespondenceNumber : "رقم المعاملة",
	auditCorrespondenceType : "نوع المعاملة",
	auditCorrespondenceHijriYear : "السنة الهجرية",
	exportReportButton : "تصدير لاكسل",
	auditReportButton : "بحث",
	auditOperationHijriDate : "التاريخ",
	auditOperationID : "رقم العملية",
	auditDocumentId : "رقم الوثيقة",
	auditDocumentTitle : "عنوان الوثيقة",
	auditOtherInfo : "أخرى",
	auditApplicatoinName : "مصدر العملية",

	Copy_Permissions : "نسخ صلاحيات لموظف اخر",
	USERSIGNATURE : "توقيع المستخدم",
	SIGN : "توقيع",
	SAVESIGNATURE : "حفظ التوقيع",
	CLEARSIGNATURE : "تفريغ التوقيع",

	Organization_Structure : "الهيكل الاداري",

	UnifiedActionMessage : " ييتم الإجراء الموحد على جميع المعاملات ماعدا : اشعار القراءة - التذكير ",
	Instruction_empty : "لم تكتب توجيهات",
	Error_No_Selected_Participants : "لم يتم اختيار المستخدمين",
	ISITLock : "محجوزة",
	Sender_Mail_Address : "رقم البريد",
	Notfiation_Message : "رسالة اعلام بالقراءة",
	SendBy_validate_error : "الرجاء اختيار طريقة التسليم",
	recievedway_validate_error : "الرجاء اختيار طريقة  الاستلام ",
	GetTypes_validate_error : "الرجاء اختيار نوع المعاملة",
	GetCategories_validate_error : "الرجاء اختيار تصنيف المعاملة",
	can_not_add_two_destination_with_same_original : "لا يمكن اضافة جهة اخرى  'اصل' لنوغ الخطاب ",
	Unified_Action_not_applicable : "لا يمكن تطبيق الاجراء الموحد على المعاملات المختارة",

	main_Unified_Notfication : "سيتم الاجراء الموحد على جميع المعاملات المختارة باستثناء",
	Internal_OLD_Text : "من معاملات الاحالات الداخلية القديمة",
	Outgoing_OLD_Text : "من معاملات الصادرة القديمة",
	Incoming_OLD_Text : "من معاملات الواردة القديمة",
	Technical_OLD_Text : "من معاملات االفنية",
	NotficationRead_Text : "اشعارات القراءة",
	Unifed_Actions_for_Applicable_Correspondence : "الاجراء الموحد للمعاملات",

	Instructions_for_Unified_Correspondence : "توجيهات المستخدمين على جميع المعاملات التي تنطبق عليها الاجراء الموحد",
	To_All_Users : "لجميع المستخدمين",
	related_with_other : "يوجد معاملات مرتبطة",
	Has_Been_Deliverd : "تم التسليم",
	PhysicalAttachment_Description : "وصف  المرفق العيني",

	AttachmentQuantity : "عدد المرفق العيني",
	Physical_attachment_informatio_error : "الرجاء التأكد من وصف و عدد المرفقات العينية",

	PhysicalAttachmentCOmmentsisMissing : "مطلوب وصف المرفقات العينية (الملاحظات) في حالة هذا النوع من المرفقات العينية",
	HLP_PhysicalAttachment : "حقل لوصف  المرفق العيني مع اخذ بعين الاعتبار تحديد عدد او كمية المرفقات العينية",
	operationsOnAttachements : "العمليات علي المرفقات",
	manageAttachements : "إدارة المرفقات",
	allFiles : "كل الملفات",
	allPictures : "كل الصور",
	pdfFiles : "   ملفات بصيغة (PDF) ",
	microsoftOfficeFiles : "ملفات الكتابة ",
	DestinationNAMESearch : "البحث بإسم الجهة",
	SearchOutgoingCorresspondences : "البحث علي المعاملات الصادرة",
	HY_CORR_validate_error : "الرجاء إدخال رقم المعاملة والسنة الهجرية",
	DELEVRY_TYPE_VALIDATE_ERROR : "الرجاء إختيار طريقة إرسال صحيحة",
	DESTINATION_VALIDATE_ERROR : "تم إضافة هذه الجهة الخارجية من قبل ",
	DESTINATIO_DELEVRY_LETTER_VALIDATE_ERROR : "الرجاء إختيار الجهة الخارجية وطريقة الإرسال ونوع الخطاب",
	GRIDROW_NOTSELECTED_VALIDATE_ERROR : "لم يتم اختيار شيء لتعديله الرجاء إختيار المراد تعديله",
	DELEVRY_REPEAT_VALIDATE_ERROR : "طريقة الإرسال موجودة بالفعل الرجاء إختيار طريقة إرسال أخرى",
	Followup_Execute : "تنفيذ تعيين المراقبين",

	create_new_SHL_outgoing_correspondence : "إنشاء معاملة صادر خارجي الى نظام سهل",
	create_new_SHL_outgoing_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في المعاملات الصادرة الى نظام سهل بوزارة التجارة و الاستثمار لايجاد المعامل",

	outgoing_shl_correspondence_information_label : "معلومات المعاملة الصادرة الى نظام سهل",

	PhysicalAttachmentnumberisMissing : "مطلوب ادخال كمية المرفقات العينية",

	Date_format_validate_error : "الرجاء اختيار تاريخ صحيح",

	confidentiality_Value_validate_error : "الرجاء اختيار قيمة السرية بشكل صحيح",
	create_new_FastAction_correspondence_label : "إنشاء معاملة عاجلة",
	OneWord_correspondence_subject_label : "الموضوع",
	yesserCheck : "يسر",
	error_on_Select_Delegating_Employee : "لم يتم اختيار الموظف البديل او المفوض باكمال اعمالك خلال فترة غيابك",
	ControlAttachements : "التحكم في المرفقات التي يقبلها نظام معاملات",
	attachementTypeErrorTitle : "خطأ فى إختيار نوع الملف",
	attachementTypeImageOfficePDF : "لابد من إختيار ملف من نوع صورة أو ملفات الكتابة أو (PDF)",
	attachementTypePDF : "لابد من إختيار ملف من نوع(PDF)",
	attachementTypeImagePDF : "لابد من إختيار ملف من نوع صورة أو (PDF)",
	attachementTypeOfficePDF : "لابد من إختيار ملف من نوع  ملفات الكتابة أو (PDF)",
	attachementTypeImage : "لابد من إختيار ملف من نوع صورة ",
	attachementTypeOffice : "لابد من إختيار ملف من نوع ملفات الكتابة ",
	attachementTypeImageOffice : "لابد من إختيار ملف من نوع صورة أو ملفات الكتابة",

	OneWord_correspondence_subject_label : "الموضوع",
	error_no_FAST_ACTION_transfered_workflow_found : "حدث خطأ، لم يتم العثور على مسار العمل خاص باجراء العمل السريع",
	error_URL_parameter_for_Quick_Action_workClassName_is_missing : "حدث خطأ بسبب فقدان احد اقسام عنوان رابط الاتصال من اجراء العمل السريع ",
	QUickTask_correspondence_information_label : "معلومات الاجراء السريع",
	QUIC_Task_action_label : "نوع و اعدادات المهام  السريع",
	Action_forQuickTask_Correspondence : "اجراءات المهام السريعة ",
	Instructions_for_QuickAction_Correspondence : "التوجيهات / التعليمات",
	error_on_Select_Delegating_Employee : "لم يتم اختيار الموظف البديل او المفوض باكمال اعمالك خلال فترة غيابك",
	FastAction : "مهمة عاجلة",

	Reminder_for_fastAction : "تذكير بمهمة عاجلة",
	CC_for_fastAction : "صورة من مهمة عاجلة",

	QUickTask_correspondence_information_label : "معلومات المهمة العاجلة",

	FastAction_correspondence_label : "متابعة اعمال المعاملة العاجلة",
	Editing_QUickTask_correspondence : "لتعديل المهمة العاجلة",

	View_Quick_correspondence_properties_setIntroText : "مكن الاستفادة من حقول الفهرسة للبحث على المهمة العاجلة ",
	Quick_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في المهام العاجلة لايجادها .",
	StepProcessor_Quick_correspondence_setIntroText : "يمكنك الاستفادة من القيم التي تم ادخالها في البحث عن المهام العاجلة لايجادها",
	externalDuplication : "تم إضافة هذه الجهة من قبل",
	externalNull : "الرجاء إدخال إسم الجهة المراد إضافتها",
	public_queue_history_dialog_title : "احالات الصندوق العام",
	// SHL
	MCINumber : " رقم المعاملة في نظام سهل",
	MCIHijriYear : "السنة الهجرية في نظام سهل",
	Corr_Status : "حالة المعاملة في نظام سهل",
	HLP_MCINumber : "رقم المعاملة  في نظام سهل بوزراة التجارة والاستثمار التي تريد الرد عليها",
	HLP_MCIHijriYear : "السنة الهجرية للمعاملة في نظام سهل بوزراة التجارة والاستثمار",
	HLP_Corr_Status : "حالة المعاملة في نظام سهل وزراة التجارة والاستثمار",
	Reply_Status : "رد علي معاملة",
	Relation_Error : "لا يمكن ربط المعاملة بنفسها",
	auditOperationDescription : "إسم  العملية",
	Correspondence_is_sent : "تم ارسال المعاملة بنجاح",
	Add_Save_Reason : "مطلوب اضافة سبب الحفظ",
	SMS_REMINDER_TXT : "تذكير معاملة من نوع:{3} موضوعها:{0} رقم :{1} تاريخ :{2}",
	fromDateLabel : "من: ",
	toDateLabel : "الى: ",
	searchLabel : "بحث",
	export_to_excel_label:"التصدير للاكسل",
	DateNotValid : "التاريخ غير صحيح.",
	SMS_correspondence_type_internal : "داخلي",
	SMS_correspondence_type_incoming : "وارد",
	SMS_correspondence_type_outgoing : "صادر",
	AdminPermissionsSearch : "الصلاحية :",
	PermissionSearchNotFound : "لا يوجد صلاحية بالأسم : ",
	unifiedActionLimitExceded : "الرجاء اختيار 10 معاملات كحد اقصى.",
	errorAddRemarks : "الرجاء إدخال الملاحظات.",
	errorRemoveRemarks : "لم يتم اختيار شيء لحذفه الرجاء إختيار المراد حذفه",
	logDateTime : "وقــت وتــــاريــــخ العمليــــــة",
	deletAttachment_confirmation : "هل تريد حذف المرفقات المختارة؟",
	number_of_characters_remaining :"عدد الاحرف ",
	decision_correspondence_properties_setIntroText : "القيم التي تدخلها الان, يمكن الاستفادة منها لاحقا في البحث في القرارات لايجاد المعاملة.",
    WebEditor_SAVE_WITH_SIGNITURE:"حفظ بالتوقيع",
    WebEditor_SAVE_WITHOUT_SIGNITURE:"حفظ بدون توقيع",
	hrdf_VIEW_SIGNATURE :"عرض التوقيع المخزن بتطبيق الموبايل",
	hrdf_WEBEDITOR_TITLE:"محرر النصوص",
	hrdf_DRAFT_SAVE:"حفظ مسودة الخطاب",
	hrdf_DOC_PRE:"معاينة الوثيقة",
	hrdf_SAVE_EDIT:"حفظ التعديلات",
	hrdf_STORING_SIGNATURE:"التوقيع المخزن بتطبيق الجوال",
	hrdf_MARKED:"تم التأشير بواسطة",
	hrdf_STORING_MARCKED:"التأشير المخزن بتطبيق الجوال",
	hrdf_GETTING_RESULTS:"اكتب لتحصل على نتائج",
	hrdf_ERROR_M:"رساله خطأ",
	hrdf_SELECTING_PERSON:"ابد من إختيار الشخص الموقع عنه",
	hrdf_SELECTING_BY_PERSON:"ابد من إختيار الشخص الموقع بـ",
	hrdf_SUBJECT_MUST:"لابد من إدخال الموضوع",
	hrdf_FILE_MUST:"لابد من إدخال إسم الملف",
	hrdf_SPEECH_CONTENT:"ابد من إدخال محتوى الخطاب",
	hrdr_SUBJECT_TITLE_60:"موضوع الخطاب يجب ألا يتجاوز 60 حرف",
	hrdf_WORNG:"رساله خطأ",
	hrdf_ERROR_SAVING_DRAFT:"حدث خطأ فى حفظ مسودة الخطاب",
	hrdf_SUCCES_SAVING_DRAFT:"تم حفظ مسودة الخطاب بنجاح",
	hrdf_NO_CHANGE:"لا يوجد تعديلات للحفظ",
	hrdf_ERROR_SAVING_CHANGES:"حدث خطأ فى حفظ التعديلات على الخطاب",
	hrdf_SUCCES_SAVING_EDITING:"تم حفظ التعديلات بنجاح",
	hrdf_NAME_MUST:"لابد من إخال إسم قالب الإدخال",
	hrdf_TEMPLAE_CONTENT_MUST:"لابد من إدخال محتوى القالب",
	hrdf_ERROR_TEMPLATE_SAVING:"حدث خطأ فى حفظ القالب",
	hrdf_TEMPLATE_SUCC:"تم حفظ القالب بنجاح",
	hrdf_PERSON_CHOOSING_MUST:"لابد من إختيار الشخص الموقع عنه",
	hrdf_SAVED_SUCC:"تم الحفظ بالتوقيع بنجاح",
	hrdf_SAVED_ERROR:"حدث خطأ فى الحفظ",
	hrdf_SAVED_NO_SIGNING:"تم الحفظ بدون توقيع بنجاح",
	hrdf_REMOVED_TEMPLATE_SUCC:"تم حذف القالب بنجاح",
/////Template File 
	hrdf_NAME_ATTACHMENT:"إسم المرفق",
	hrdf_SUBJECT_SPEECH:"موضوع الخطاب",
	hrdf_PRIORITY_LEVEL:"درجة الاهمية",
	hrdf_POSITION:"المنصب",
	hrdf_ADJECTIVE:"الصفة",
	hrdf_SELECT_BANNER:"إختر  الترويسة",
	hrdf_INPUT_TEMPLATES:"قوالب الإدخال",
	hrdf_ATTACHMENT_SETTINGS_BARCODE:"إعدادات المرفقات فى الباركود",
	hrdf_CURRENT_MANAGEMENT_CURRENT_TIME:"الإدارة الحالية والوقت الحالى",
	hrdf_ATTACHMENTS_ADDED_CURRENT_USER:"المرفقات المضافة بواسطة المستخدم الحالى",
	hrdf_VIEW_SIGNATURE_PREVIEW:"عرض التوقيع فى المعاينه",
	hrdf_USING_WORDS_NUMBERING:"إستخدام الكلمات فى الترقيم (اولا, ثانيا)",
	hrdf_ADMIN_SETTINGS_HEADER:"إعدادات الإدارة فى الترويسه",
	hrdf_ADDIND_MANAGEMENT_HEADER:"إضافه الإدارة فى الترويسه",
	hrdf_ADDING_CURRENT_ADMINISTRATION:"إضافه الإداره الحاليه",
	hrdf_ADD_MANAGEMENT_CREATED_LETTER:"إضافه الإدارة المنشئه للخطاب",
	hrdf_ABOUT:"توقـيع عـن",
	hrdf_ADDING_IMAGES_SPEECH:"إضافه صور للخطاب",
	hrdf_ADDING_SIGNATURE_PHOTO_VERSION:"إضافه التوقيع فى نسخه الصور",
	hrdf_IMAGE_FORMAT:"صيغه الصور",
	hrdf_ADDING_VISA_LETTER:"إضافة تأشيرةعلى الخطاب",
	hrdf_INPUT_TEMPLATE_NAME:"إسم قالب الإدخال",
	hrdf_ADDING_INPUT_TEMPLATE:"إضافة كقالب إدخال",
	hrdf_VIEW_SIGNATURE_STORED_MOBILE_APP:"عرض التوقيع المخزن بتطبيق الجوال",
	hrdf_SHOW_YOUR_STORED_TAG_MOBILE_APP:"عرض التأشير المخزن بتطبيق الجوال",
	hrdf_TRANSACTION_ATTACHMENTS:"مرفقات المعاملة",
	hrdf_DELETION:"حذف",
	/////WEBEditorLetterHistory JS
    hrdf_RECORD_MOVEMENTS:"سجل حركات مسوده الخطاب",
    hrdf_History_REVIEW:"إستعراض",					
//// WEBEditorTemplateFeature 
    hrdf_TEMPLATE_NAME:"إسم القالب",
    hrdf_CHOOSING_YOUR_USERNAME:"اختر اسم المستخدم",
    hrdf_SELECTING_HEADER_NAME:"إختر اسم الترويسة",
    hrdf_ADDITION:"إضافة",
    hrdf_MODIFY:"تعديل",
    hrdf_NEW:"جديد",
    hrdf_SHOWTRACK:"عرض المسار",
    hrdf_CHOOSING_USERNAME_FILTER:"اختر اسم المستخدم للتصفية",
//////trackCorresponding   JS
    hrdf_TRANSACTION_TRACKING_Title:":تتبع المعاملة  ",
//////tarckCorresponding   Template
    hrdf_OPERATOR_INFORMATION:":معلومات المشغل",
    hrdf_ADMINISTRATION:":الإدارة ",
    hrdf_START_DATE_OPERATION:" :تاريخ بدأ التشغيل  ",
	read : "مقروءة",
	unread : "غير مقروءة",
	Currepondance_is_closed : "تم انهاء وإقفال المعاملات بنجاح ",
	Unifed_Action_TO_End_And_Close_Coresspondences : "الإجراء الموحد لإنهاء وإقفال المعاملات",
	importCoresspondence : "توريد معاملة منشأة سابقا",
	exportCoresspondence : "تصدير معاملة منشأة سابقا",
	selectDepartmentToSend : "الإدارة المراد الإرسال بها",
	sighWith :"توقيع بـ",
	departmentToSendWithError: "يرجى اختيار الادارة المراد الارسال بها" ,
	replyToSenderMsg:  "لقد اخترت الرد على المرسل",
	selectDepartment: "اختيار الادارة",
	selectUser: "اختر المستخدم",
	selectPermission: "نوع الصلاحية",
	ownerList : "قائمة المالك",
	viewerList: "قائمة المشاهد",
	applySecurity: "تطبيق السرية",
	from_employee: "من الموظف",
	to_employee: "الى الموظف",
	reassign_cross: "نقل المعاملات"
		
	
	
	
	


});