/*
 * Licensed Materials - Property of IBM
 * (C) Copyright IBM Corp. 2010, 2017
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */
define([
	"dojo/_base/declare",
	"./ErrorDialog"
], function(declare, ErrorDialog) {

	/**
	 * @name ecm.widget.dialog.WarningDialog
	 * @class Provides a dialog box that is used to display a warning message that was generated by a service request.
	 *        This dialog can be connected to the <code>onMessageAdded</code> event of <code>ecm.model.desktop</code>
	 *        to listen to response messages and automatically display a warning dialogs for warnings returned from
	 *        requests to the server.
	 * @augments ecm.widget.dialog.ErrorDialog
	 * @since 2.0.3.3
	 */
	return declare("ecm.widget.dialog.WarningDialog", [
		ErrorDialog
	], {
		/** @lends ecm.widget.dialog.WarningDialog.prototype */

		baseClass: "ecmWarningDialog dijitDialog minor",

		messageAddedHandler: function(message) {
			// Overrides ecm.widget.dialog.ErrorDialog.messageAddedHandler() to display warning messages
			if (message.level == 1 && !message.backgroundRequest)
				this.showMessage(message);
		}
	});
});
